VAGRANTFILE_API_VERSION = "2"                                          
                                                                       
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|                 
                                                                       
  # Every Vagrant virtual environment requires a box to build off of.  
  config.vm.box = "ubuntu/trusty64"                                    
  config.vm.provision :shell, path: "bootstrap.sh"                                                                   
end
